services:
  vectordb:
    build:
      context: .
      dockerfile: Dockerfile.vectordb  
    container_name: chroma_docker
    environment:
      - CHROMA_TELEMETRY_ANONYMOUS=false
      - CHROMA_LOG_CONFIG=/chromadb/log_config.yml
    networks:
      - my_network
    ports:
      - 8800:8000
    volumes:
      - ./chromadb:/chromadb
      - ./chromadb/log_config.yml:/chromadb/log_config.yml


  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: hello123
      MYSQL_DATABASE: fyp_db
    networks:
      - my_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  scraper:
    build:
      context: ./
    container_name: scraper
    environment:
      - APP_ID=861942379371299
      - APP_SECRET=760999b7887a59c7bcb6a642e83d9c9a
      - INSTAGRAM_USER_ID=17841469360862189
      - OPENAI_API_KEY=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
      - AZURE_BLOB_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=scraperoutput;AccountKey=KZtFddCQ5u4QZhltrUrhUg1uqJgmWEaG7ZnApwVk0pHVqM7/Ag5ON1ChzHf0MVTSEkNBISNU2jyn+AStJqiGjQ==;EndpointSuffix=core.windows.net 
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:hello123@mysql-container:3306/fyp_db
    networks:
      - my_network
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-standalone-chrome
    ports:
      - "4444:4444"  # Expose Selenium's default port for remote connection
    networks:
      - my_network
    environment:
      - SE_NODE_MAX_SESSION=5  # Optional: You can set the maximum number of sessions
    volumes:
      - /dev/shm:/dev/shm  # To avoid shared memory issues with Chrome

networks:
  my_network:
    # driver: bridge
  chroma_network:

volumes:
  mysql_data:
