services:
  vectordb:
    build:
      context: .
      dockerfile: Dockerfile.vectordb  
    container_name: chroma_docker
    environment:
      - CHROMA_TELEMETRY_ANONYMOUS=false
      - CHROMA_LOG_CONFIG=/chromadb/log_config.yml
    networks:
      - my_network
    ports:
      - 8800:8000
    volumes:
      - ./chromadb:/chromadb
      - ./chromadb/log_config.yml:/chromadb/log_config.yml


  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: hello123
      MYSQL_DATABASE: fyp_db
    networks:
      - my_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  scraper:
    build:
      context: ./
    container_name: scraper
    environment:

    networks:
      - my_network
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-standalone-chrome
    ports:
      - "4444:4444"  # Expose Selenium's default port for remote connection
    networks:
      - my_network
    environment:
      - SE_NODE_MAX_SESSION=5  # Optional: You can set the maximum number of sessions
    volumes:
      - /dev/shm:/dev/shm  # To avoid shared memory issues with Chrome

networks:
  my_network:
    # driver: bridge
  chroma_network:

volumes:
  mysql_data:
